name = "sluggy"
version = "0.1.0"

description = "A lightweight, SEO-oriented slug library for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowlabs-hq", repo = "sluggy" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
